### ISSUE TITLE
Editor: Mirror icon is wrong

### ISSUE THREAD

**Issue by Wuzzy2** [SimonN/LixD#349] opened 2018-06-28 15:57 UTC
In Lix 0.9.17, the icon for mirroring an object (horizontally) looks wrong. The arrows go up/down, but this suggests the mirror is vertical.

The arrows should go left/right instead beause this tool only mirrors objects horizontally, not vertically.

**Comment by SimonN** [comment] 2018-06-29 19:35
Duplicate of #115 Editor, single flip button inconsistent, make 2nd button.

I agree, there should be an icon to mirror horizontally.

**Closed** 2018-09-23 17:42 UTC
Labels: 3-bug
